# Configuration Jekyll ultra-minimale pour GitHub Pages
title: "PaniniFS"
description: "Site migré vers paninifs.org"
baseurl: ""
url: "https://stephanedenis.github.io"

# Plugins minimaux
plugins:
  - jekyll-feed

# Exclusions
exclude:
  - README.md
  - Gemfile*
  - "*.backup"

# 🏕️ Configuration minimale pour éviter tout échec Jekyll
