# Configuration Jekyll minimale pour GitHub Pages
# ==============================================
# 
# Configuration de base pour éviter les échecs de build
# et rediriger vers le site MkDocs principal.

title: "PaniniFS - Site migré"
description: "Infrastructure externalisée - Redirection vers paninifs.org"

# Configuration Jekyll
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Paramètres de base
baseurl: ""
url: "https://stephanedenis.github.io"

# Redirection globale vers nouveau site
# collections_dir: false

# Exclusions
exclude:
  - docs_new/
  - TEST_WORKFLOW_OUTPUT/
  - "*.log"
  - "*.tmp"
  - README.md
  - Gemfile*
  - node_modules/
  - vendor/

# 🏕️ Camping Strategy: Site Jekyll minimal avec redirection
# Site principal maintenant hébergé sur paninifs.org via MkDocs
