name: Copilotage CI
on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GIT_PAGER: cat
      GH_PAGER: cat
      PAGER: cat
      LESS: FRSX
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: false
      - name: Validate copilotage tree exists (case-insensitive)
        shell: bash
        run: |
          set -euo pipefail
          if [ -d Copilotage ]; then BASE=Copilotage; elif [ -d copilotage ]; then BASE=copilotage; else echo "missing Copilotage/ (or copilotage/)"; exit 1; fi
          echo "Detected: $BASE"
          test -d "$BASE" || { echo "missing $BASE/"; exit 1; }
          test -d "$BASE/shared" || { echo "missing $BASE/shared"; exit 1; }
