name: copilotage-journal-index (light)

on:
  push: {}
  pull_request: {}

jobs:
  index:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate journal index (no commit)
        run: |
          set -e
          chmod +x Copilotage/scripts/devops/journal_index.sh
          Copilotage/scripts/devops/journal_index.sh >/tmp/jfile_path 2>/dev/null || true
          # Afficher diff éventuel sans échouer le job
          if git diff --quiet -- Copilotage/journal/INDEX.md; then
            echo "Index à jour."
          else
            echo "::warning::Copilotage/journal/INDEX.md n'est pas à jour. Exécutez setup_dev_environment.sh pour installer le hook pre-commit ou lancez journal_index.sh localement."
            git --no-pager diff -- Copilotage/journal/INDEX.md | sed 's/^/    /'
          fi