name: Copilotage CI
on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: false
      # Pas d'init récursif: le job ne dépend pas des submodules
      # - run: git submodule update --init --recursive
      - name: Validate Copilotage layout
        run: |
          set -euo pipefail
          # Dossier principal requis (respecte la casse)
          if [ ! -d "Copilotage" ]; then
            echo "::error::Missing required directory: Copilotage/";
            exit 1;
          fi
          # Dossier shared optionnel
          if [ ! -d "Copilotage/shared" ]; then
            echo "::notice::Optional directory Copilotage/shared not found; skipping related checks.";
          fi
