name: Deploy MkDocs Site
permissions:
  contents: write

on:
  push:
    branches: [ master, main ]
    paths:
      - 'docs_new/**'
      - 'modules/**/docs/**'
      - 'mkdocs.yml'
      - 'CNAME'
      - '.github/workflows/deploy-docs.yml'
  pull_request:
    branches: [ master, main ]
    paths:
      - 'docs_new/**'
      - 'modules/**/docs/**'
      - 'mkdocs.yml'
      - '.github/workflows/deploy-docs.yml'
  workflow_dispatch:

jobs:
  build-deploy:
    concurrency:
      group: deploy-docs
      cancel-in-progress: true
    runs-on: ubuntu-latest
    env:
      GIT_PAGER: cat
      GH_PAGER: cat
      PAGER: cat
      LESS: FRSX

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: false

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install MkDocs deps
        run: |
          pip install -r docs_new/requirements.txt

      - name: Generate modules docs index (no-op if script missing)
        run: |
          if [ -f scripts/devops/generate_modules_index.py ]; then \
            python3 scripts/devops/generate_modules_index.py; \
          else \
            echo "No generate_modules_index.py found, skipping"; \
          fi

      - name: Build site
        env:
          KROKI_URL: https://kroki.io
        run: |
          mkdocs build --strict --config-file mkdocs.yml

      - name: Deploy to GitHub Pages
        if: github.event_name == 'push' && (github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main')
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
          cname: paninifs.org

      - name: Success
        run: |
          echo "Site built and deployed to https://paninifs.org"
