name: Deploy Docs Auto
permissions:
  contents: write

on:
  push:
    branches: [ master, main, ci/terminal-stability ]
    paths:
      - '.github/ops/triggers/deploy-docs.txt'

jobs:
  auto-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install MkDocs deps
        run: |
          pip install -r docs_new/requirements.txt

      - name: Generate modules docs index
        run: |
          python3 scripts/generate_modules_docs_index.py

      - name: Build site
        env:
          KROKI_URL: https://kroki.io
        run: |
          mkdocs build --strict --config-file mkdocs.yml

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
          cname: paninifs.org

      - name: Verify live
        run: |
          curl -I -L --max-time 20 https://paninifs.org || true