name: Deploy MkDocs Site
permissions:
  contents: write

on:
  push:
    branches: [ master, main ]
    paths:
      - 'docs_new/**'
      - 'modules/**/docs/**'
      - 'mkdocs.yml'
      - '.github/workflows/deploy-docs.yml'
  workflow_dispatch:
    inputs:
      force_deploy:
        description: 'Forcer le déploiement (utile hors main/master)'
        required: false
        default: 'false'

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: deploy-docs
      cancel-in-progress: false

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: false

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install MkDocs deps
        run: |
          pip install -r docs_new/requirements.txt
          pip install jq

      - name: Generate modules docs index
        run: |
          python3 scripts/generate_modules_docs_index.py

      - name: Build site
        env:
          KROKI_URL: https://kroki.io
        run: |
          mkdocs build --strict --config-file mkdocs.yml

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
          cname: paninifs.org

      - name: Publish site to /docs (Pages legacy source)
        if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main'
        run: |
          set -e
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          # Préserver CNAME si présent dans /docs
          if [ -f docs/CNAME ]; then cp docs/CNAME /tmp/CNAME || true; fi
          rm -rf docs/*
          mkdir -p docs
          cp -a site/* docs/
          if [ -f /tmp/CNAME ]; then mv /tmp/CNAME docs/CNAME; fi
          git add -A docs
          git commit -m "docs(build): sync MkDocs output to /docs [skip ci]" || true
          git push origin HEAD

      - name: Success
        run: |
          echo "Site built and deployed to https://paninifs.org"
