name: Build Docs (MkDocs)

on:
  push:
    branches: [ master, main, fix/**, feat/**, docs/** ]
    paths:
      - 'mkdocs.yml'
      - 'docs_new/**'
  pull_request:
    types: [opened, synchronize, reopened, edited]
    paths:
      - 'mkdocs.yml'
      - 'docs_new/**'

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs mkdocs-material mkdocs-static-i18n mkdocs-kroki-plugin mkdocs-git-revision-date-localized-plugin pymdown-extensions
      - name: Build
        run: |
          mkdocs build --config-file mkdocs.yml --strict
