name: Label PRs by Agent

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  label-by-agent:
    runs-on: ubuntu-latest
    steps:
      - name: Derive agent/session from PR and add labels
        uses: actions/github-script@v7
        with:
          script: |
            const pr = context.payload.pull_request;
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            const number = pr.number;

            const title = pr.title || '';
            const headRef = pr.head && pr.head.ref ? pr.head.ref : '';

            // Extract identifiers from title: [journal:HOST-pidPID] and/or [agent:HOST]
            let agent = null;
            let journalHost = null;
            let journalPid = null;

            const journalMatch = title.match(/\[journal:([A-Za-z0-9._-]+)-pid(\d+)\]/i);
            if (journalMatch) {
              journalHost = journalMatch[1];
              journalPid = journalMatch[2];
              agent = journalHost; // Derive agent from journal host
            }

            const agentMatch = title.match(/\[agent:([A-Za-z0-9._-]+)\]/i);
            if (!agent && agentMatch) {
              agent = agentMatch[1];
            }

            // Fallbacks: branch patterns like agents/ID/... or agent-ID/...
            if (!agent && headRef) {
              let m = headRef.match(/^agents?\/([^\/]+)/i);
              if (!m) m = headRef.match(/^agent-([^\/]+)/i);
              if (m) agent = m[1];
            }

            // Nothing detected? Skip gracefully
            if (!agent && !journalHost) {
              core.info('No agent or journal identifier found; skipping labels.');
              return;
            }

            // Compute labels to apply
            const labelsToApply = [];
            if (agent) labelsToApply.push(`agent:${agent.toLowerCase()}`);
            if (journalHost && journalPid) labelsToApply.push(`journal:${journalHost.toLowerCase()}-pid${journalPid}`);

            if (!labelsToApply.length) {
              core.info('Nothing to label.');
              return;
            }

            // Ensure label exists
            async function ensureLabel(name) {
              try {
                await github.rest.issues.getLabel({ owner, repo, name });
                return;
              } catch (e) {
                // Create label with a default color; ignore if already exists due to race
                try {
                  await github.rest.issues.createLabel({ owner, repo, name, color: 'BFD4F2', description: 'PRs ouvertes par un agent spécifique' });
                } catch (e2) {
                  core.info(`Label create ignored: ${e2.message}`);
                }
              }
            }

            for (const lbl of labelsToApply) {
              await ensureLabel(lbl);
            }
            await github.rest.issues.addLabels({ owner, repo, issue_number: number, labels: labelsToApply });
            core.info(`Applied labels ${labelsToApply.join(', ')} to PR #${number}`);