name: Provenance Guardian

on:
  schedule:
    - cron: "*/15 * * * *"
  workflow_dispatch: {}
  pull_request:
    types: [opened, edited, synchronize, reopened, labeled, unlabeled]

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  guard:
    runs-on: ubuntu-latest
    steps:
      - name: Ensure labels exist
        uses: actions/github-script@v7
        with:
          script: |
            const ensure = async (name, description) => {
              try {
                await github.rest.issues.getLabel({ owner: context.repo.owner, repo: context.repo.repo, name });
              } catch {
                try {
                  await github.rest.issues.createLabel({ owner: context.repo.owner, repo: context.repo.repo, name, color: 'BFD4F2', description });
                } catch {}
              }
            };
            await ensure('needs-provenance', 'PR manque les labels de provenance');
            await ensure('autofill-provenance', 'Autorise l’autoremplissage des labels de provenance par le guardian');
      - name: Guard open PRs for provenance labels
        uses: actions/github-script@v7
        with:
          script: |
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            const { data: prs } = await github.rest.pulls.list({ owner, repo, state: 'open', per_page: 50 });
            const runId = process.env.GITHUB_RUN_ID || String(Date.now());
            const hostVal = 'gha-runner';
            for (const pr of prs) {
              const number = pr.number;
              const labels = (pr.labels || []).map(l => l.name);
              const hasHost = labels.some(n => /^prov:host=/i.test(n));
              const hasPid = labels.some(n => /^prov:pid=/i.test(n));
              const hasAgent = labels.some(n => /^agent:/i.test(n));
              const hasModel = labels.some(n => /^model:/i.test(n));
              const hasOwner = labels.some(n => /^owner:/i.test(n));
              const missing = [];
              if (!hasHost) missing.push('prov:host=<...>');
              if (!hasPid) missing.push('prov:pid=<...>');
              if (!hasAgent) missing.push('agent:<...>');
              if (!hasModel) missing.push('model:<...>');
              if (!hasOwner) missing.push('owner:<...>');
              if (!missing.length) continue;

              // Mark as needs-provenance
              await github.rest.issues.addLabels({ owner, repo, issue_number: number, labels: ['needs-provenance'] }).catch(() => {});

              // Autofill if authorized
              const allowAuto = labels.includes('autofill-provenance');
              if (!allowAuto) continue;

              const toAdd = [];
              if (!hasHost) toAdd.push(`prov:host=${hostVal}`);
              if (!hasPid) toAdd.push(`prov:pid=${runId}`);
              if (!hasAgent) toAdd.push('agent:GitHubCopilot');
              if (!hasModel) toAdd.push('model:unspecified');
              if (!hasOwner) toAdd.push('owner:agent');

              // Ensure labels exist then add
              for (const name of toAdd) {
                try { await github.rest.issues.getLabel({ owner, repo, name }); }
                catch { try { await github.rest.issues.createLabel({ owner, repo, name, color: 'BFD4F2', description: 'Provenance/agent metadata' }); } catch {} }
              }
              if (toAdd.length) {
                await github.rest.issues.addLabels({ owner, repo, issue_number: number, labels: toAdd }).catch(() => {});
              }
            }
